### ISSUE TITLE
interaction with i3: armor not usable

### ISSUE THREAD

**Issue by ademant** [mt-mods/xp_redo_ranks_ores#4]
Using booth mods i3 and xp_redo_ranks_ores lead to following situation:
New armor can't be attached to avatar.

Situation with dev-minetest (5.8.0) on a debian server. Moved mod for mod into mod-folder, so I could identify xp_redo_ranks_ores to interfere with i3.
Versions:
i3: https://github.com/minetest-mods/i3 commit 9437545ddb629425ddca53d9ef551e29c1810b6a, tag: 1.16.2
xp_redo_ranks_ores: https://github.com/mt-mods/xp_redo_ranks_ores commit 1a034425deb686201d42911fbcfe86c03f13cd5c

**Comment by ademant** [comment]
![screenshot_20230523_073628](https://github.com/mt-mods/xp_redo_ranks_ores/assets/40039199/2ab30810-2b66-4bfc-b11a-524a0915dd1a)

**Comment by S-S-X** [comment]
Does this work with latest release version 5.7.0 or does it have same issue?

**Comment by ademant** [comment]
Installed 5.7.0 from ubuntu/ppa. Same issue. On cli following warning:

2023-05-23 15:00:42: WARNING[Main]: GUIInventoryList::draw(): The inventory location "detached:@#ff0000)singleplayer@#ffffff)_armor" doesn't exist

to reproduce with 5.7.0:
1. select 3d_armor and i3
2. create armor (wooden boots for me) and attach as armor
3. quit and select xp_redo and xp_redo_ranks_ore
4. start again and see that 3D armor in i3 not usable any more.

**Comment by OgelGames** [comment]
Here's the problem, i3 changed to reading the nametag instead of the player name: https://github.com/minetest-mods/i3/commit/080579b2a4cd7f674e946430ca11ade2fe1ac4ef

**Comment by OgelGames** [comment]
Opened an issue for i3: https://github.com/minetest-mods/i3/issues/98

Closing this, it has nothing to do with this mod. (any mod that colors the player's nametag will cause this bug)

**Comment by ademant** [comment]
But coloring the player's nametag is not forbidden, so this mod should be able to handle it.

**Comment by S-S-X** [comment]
> But coloring the player's nametag is not forbidden, so this mod should be able to handle it.

Situation is that this mod does (adds color) it but i3 cannot handle it but fails when it is colored.
